version: 2
updates:

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "development"
    schedule:
      interval: "monthly"

  # Maintain dependencies for Composer
  - package-ecosystem: "composer"
    directory: "/"
    target-branch: "development"
    schedule:
      interval: "monthly"
